### ISSUE TITLE
Bad Argument

### ISSUE THREAD

**Issue by ezgoodnight** [coderofsalvation/hubot-script-shellcmd#1]
I installed and created helloworld as directed and I'm getting: ERROR TypeError: Bad argument

Curious if something is installed wrong or you have any insights?

Full text as follows from Shell:

```
mega> [Wed Mar 18 2015 17:04:35 GMT-0400 (EDT)] ERROR TypeError: Bad argument
  at ChildProcess.spawn (child_process.js:923:24)
  at exports.spawn (child_process.js:723:9)
  at run_cmd (/home/user/hubot/node_modules/hubot-script-shellcmd/src/shellcmd.coffee:23:5, <js>:7:15)
  at TextListener.callback (/home/user/hubot/node_modules/hubot-script-shellcmd/src/shellcmd.coffee:30:5, <js>:18:14)
  at executeListener (/home/user/hubot/node_modules/hubot/src/listener.coffee:54:11, <js>:44:19)
  at allDone (/home/user/hubot/node_modules/hubot/src/robot.coffee:253:37, <js>:172:16)
  at /home/user/hubot/node_modules/hubot/node_modules/async/lib/async.js:277:13
  at Object.async.eachSeries (/home/user/hubot/node_modules/hubot/node_modules/async/lib/async.js:145:20)
  at Object.async.reduce (/home/user/hubot/node_modules/hubot/node_modules/async/lib/async.js:271:15)
  at /home/user/hubot/node_modules/hubot/src/robot.coffee:258:7, <js>:175:22
  at process._tickCallback (node.js:415:13)
```

**Comment by coderofsalvation** [comment]
interesting.
Does this happen during startup or when you invoke an url?
Please provide the url in case of the latter.

hope all is well

**Comment by kadu** [comment]
The same happens to me, the error happened when I send a command to hubot (@hubot: shellcmd list)

**Comment by coderofsalvation** [comment]
- did you get the 'helloworld' example to run? 
- which node version are you using? 
- does the same happen if you add an extra argument? ( 'shellcmd list foo' instead of 'shellcmd list' )

I might be able to replicate the error.

**Comment by sheltonli** [comment]
I am also getting the same issue. I am unable to run shellcmd or shellcmd helloworld. I'm using node v0.12.2.

Let me know what other info I can provide you.

**Comment by litch** [comment]
I'm having the same problem:

```
ubuntu@ip-10-0-0-246:~/hubot$ node -v
v0.10.25

ubuntu@ip-10-0-0-246:~/hubot$  bin/hubot
[Sat Jun 20 2015 13:03:56 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
hubot> 
hubot> 
hubot> shellcmd
hubot> shellcmd list
hubot> hubot shellcmd list
[Sat Jun 20 2015 13:04:09 GMT+0000 (UTC)] ERROR TypeError: Bad argument
  at ChildProcess.spawn (child_process.js:923:24)
  at exports.spawn (child_process.js:723:9)
  at run_cmd (/home/ubuntu/hubot/node_modules/hubot-script-shellcmd/src/shellcmd.coffee:23:5, <js>:7:15)
  at TextListener.callback (/home/ubuntu/hubot/node_modules/hubot-script-shellcmd/src/shellcmd.coffee:37:5, <js>:28:14)
  at TextListener.Listener.call (/home/ubuntu/hubot/node_modules/hubot/src/listener.coffee:43:7, <js>:37:14)
  at Robot.receive (/home/ubuntu/hubot/node_modules/hubot/src/robot.coffee:230:9, <js>:154:33)
  at Shell.Adapter.receive (/home/ubuntu/hubot/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at [object Object].listener (/home/ubuntu/hubot/node_modules/hubot/src/adapters/shell.coffee:48:7, <js>:92:22)
  at [object Object].Cli.parse (/home/ubuntu/hubot/node_modules/hubot/node_modules/cline/index.js:320:35)
  at [object Object].<anonymous> (/home/ubuntu/hubot/node_modules/hubot/node_modules/cline/index.js:182:18)
  at [object Object].defaultFn (/home/ubuntu/hubot/node_modules/hubot/node_modules/cline/index.js:53:13)
  at [object Object].fn (/home/ubuntu/hubot/node_modules/hubot/node_modules/cline/index.js:217:23)
  at Interface.<anonymous> (/home/ubuntu/hubot/node_modules/hubot/node_modules/cline/index.js:148:18)
  at Interface.EventEmitter.emit (events.js:95:17)
  at Interface._onLine (readline.js:202:10)
  at Interface._line (readline.js:531:8)
  at Interface._ttyWrite (readline.js:760:14)
  at ReadStream.onkeypress (readline.js:99:10)
  at ReadStream.EventEmitter.emit (events.js:98:17)
  at emitKey (readline.js:1095:12)
  at ReadStream.onData (readline.js:840:14)
  at ReadStream.EventEmitter.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:746:14)
  at ReadStream.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at ReadStream.Readable.push (_stream_readable.js:127:10)
  at TTY.onread (net.js:526:21)

hubot> hubot shellcmd
[Sat Jun 20 2015 13:04:15 GMT+0000 (UTC)] ERROR TypeError: Bad argument
  at ChildProcess.spawn (child_process.js:923:24)
  at exports.spawn (child_process.js:723:9)
  at run_cmd (/home/ubuntu/hubot/node_modules/hubot-script-shellcmd/src/shellcmd.coffee:23:5, <js>:7:15)
  at TextListener.callback (/home/ubuntu/hubot/node_modules/hubot-script-shellcmd/src/shellcmd.coffee:30:5, <js>:18:14)
  at TextListener.Listener.call (/home/ubuntu/hubot/node_modules/hubot/src/listener.coffee:43:7, <js>:37:14)
  at Robot.receive (/home/ubuntu/hubot/node_modules/hubot/src/robot.coffee:230:9, <js>:154:33)
  at Shell.Adapter.receive (/home/ubuntu/hubot/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at [object Object].listener (/home/ubuntu/hubot/node_modules/hubot/src/adapters/shell.coffee:48:7, <js>:92:22)
  at [object Object].Cli.parse (/home/ubuntu/hubot/node_modules/hubot/node_modules/cline/index.js:320:35)
  at [object Object].<anonymous> (/home/ubuntu/hubot/node_modules/hubot/node_modules/cline/index.js:182:18)
  at [object Object].defaultFn (/home/ubuntu/hubot/node_modules/hubot/node_modules/cline/index.js:53:13)
  at [object Object].fn (/home/ubuntu/hubot/node_modules/hubot/node_modules/cline/index.js:217:23)
  at Interface.<anonymous> (/home/ubuntu/hubot/node_modules/hubot/node_modules/cline/index.js:148:18)
  at Interface.EventEmitter.emit (events.js:95:17)
  at Interface._onLine (readline.js:202:10)
  at Interface._line (readline.js:531:8)
  at Interface._ttyWrite (readline.js:760:14)
  at ReadStream.onkeypress (readline.js:99:10)
  at ReadStream.EventEmitter.emit (events.js:98:17)
  at emitKey (readline.js:1095:12)
  at ReadStream.onData (readline.js:840:14)
  at ReadStream.EventEmitter.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:746:14)
  at ReadStream.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at ReadStream.Readable.push (_stream_readable.js:127:10)
  at TTY.onread (net.js:526:21)

hubot> 
```

**Comment by coderofsalvation** [comment]
Gotcha: it seems no-one provided a HUBOT_SHELLCMD environmentvariable (as mentioned in README.md)

To prevent these issues in the future, I commited a new version which falls back to a default bashscript when the user forgets to specify this:

https://github.com/coderofsalvation/hubot-script-shellcmd/commit/97db914352a867bc4eea9211c65f999d207d2751#diff-a19d409b19e1a74b946afaaedcf5b149

It will now run out of the box without any configuration.

**Comment by litch** [comment]
:+1: Thank you.
